"""Assembling the deployable: the platform handlers and the code they import.

The endpoints are ordinary Python in `paywall/`, tested here with no server
involved. What a host like Vercel wants instead is a file per route exposing a
`handler` class, importing from somewhere inside its own project directory. So
the build copies the modules the endpoints need into `deploy/api/_lib/` and
writes three thin handlers on top of them.

Copying rather than importing across the tree is deliberate. A serverless
bundle only contains what is under its project root, and the alternative —
pointing the platform at the repository root — would put the miner, the
scrapers, `playwright` and every other unrelated dependency inside the
function that hands out licences. The copy is regenerated by every build, so
it cannot drift from the source it came from.

`_lib/` and `_data/` begin with an underscore, which is how the platforms
spell "not a route": neither becomes a URL, so the paid bundle is not
downloadable and the library code is not executable from outside.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

#: Modules the endpoints import, with their packages. Everything here must be
#: importable with nothing installed: no PyYAML, no requests, no playwright.
VENDORED = {
    "paywall": (
        "__init__.py", "models.py", "licence.py", "store.py", "kv.py",
        "endpoints.py", "fulfilment.py", "serverless.py",
    ),
    "storefront": ("__init__.py", "models.py", "fulfil.py"),
}

_HANDLER = '''"""Generated by paywall.deploy — edit paywall/, not this file.

Route: POST /api/{name}
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "_lib"))

from http.server import BaseHTTPRequestHandler          # noqa: E402

from paywall.serverless import (                        # noqa: E402
    ConfigError, demo_warning, dispatch, load_runtime,
)

HERE = os.path.dirname(os.path.abspath(__file__))
_RUNTIME = None


def runtime():
    """Loaded once per instance: the paid bundle is the big part of it."""
    global _RUNTIME
    if _RUNTIME is None:
        _RUNTIME = load_runtime(HERE)
        if warning := demo_warning():
            sys.stderr.write("paywall: %s\n" % warning)
    return _RUNTIME


class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        length = int(self.headers.get("content-length") or 0)
        raw = self.rfile.read(length) if length else b""
        try:
            response = dispatch("{name}", raw, dict(self.headers.items()), runtime())
            status, body = response.status, response.body
        except ConfigError as exc:
            # A deployment mistake, not a bad request. Say so in the log and
            # keep the message out of the response body.
            sys.stderr.write("paywall: %s\\n" % exc)
            status, body = 500, {{"error": "this endpoint is not configured yet"}}
        self._send(status, body)

    def do_GET(self):
        self._send(405, {{"error": "post to this endpoint"}})

    def _send(self, status, body):
        payload = json.dumps(body).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt, *args):
        # The default writes the client's address into the log on every
        # request. The platform already logs the request line.
        sys.stderr.write("paywall {name}: " + (fmt % args) + "\\n")
'''

_VERCEL = {
    "$schema": "https://openapi.vercel.sh/vercel.json",
    "outputDirectory": "public",
    "headers": [
        {
            "source": "/(.*)",
            "headers": [
                {"key": "X-Content-Type-Options", "value": "nosniff"},
                {"key": "Referrer-Policy", "value": "strict-origin-when-cross-origin"},
                {"key": "X-Frame-Options", "value": "SAMEORIGIN"},
            ],
        }
    ],
    "rewrites": [
        {"source": "/get", "destination": "/get.html"},
        {"source": "/thanks", "destination": "/thanks.html"},
    ],
}

_README = """# Deploying this

Everything in this directory is generated by

    python -m paywall.cli build {product_path}

and committed, so the host has nothing to build. Re-run it after editing any
content, the app template, the ladder or the funnel copy, then commit what
changed.

## What is what

    public/index.html   the study app, with the free half compiled in
    public/get.html     the offer page
    public/thanks.html  the page after payment, which hands over the key
    api/unlock.py       POST a licence key, get the content it covers
    api/claim.py        POST the browser's nonce, get its key
    api/webhook.py      the provider's callback: sale in, licence out
    api/_lib/           the modules those three import, copied from the source
    api/_data/paid.json the paid half of the product — NOT under public/

`_lib` and `_data` start with an underscore, which is how Vercel spells "not a
route". Nothing under `api/` is served as a static file, so `paid.json` is not
downloadable; it is read by the functions only.

## Just want to look at it

The whole funnel runs with two environment variables and no accounts anywhere
except Vercel:

    PAYWALL_SECRET   any long random string
    PAYWALL_DEMO     1

Then the free page, the offer page, the gate panels and unlocking with a
licence key all work. Mint a key against the same secret with

    PAYWALL_SECRET=<the same value> \
      python -m paywall.cli issue {product_path} --order demo-1 --offers core,bump

and paste it into the app under **Access**.

`PAYWALL_DEMO` changes nothing about who is let in — signatures are still
verified and the webhook still needs its secret. What it does is keep the
little bit of state in memory, per instance: device counts reset when the host
recycles the instance, and the thank-you page cannot hand over a key, because
the webhook that recorded it landed somewhere else. **Do not take real
payments through a deployment with it set.** For that, read on.

## Vercel

Import the repository once, then set **Root Directory** to this directory
(`{product_path}/{deploy_name}`). Leave the build command, output directory and
install command empty — `vercel.json` here sets `outputDirectory` to `public`,
and `api/*.py` are picked up as Python functions automatically.

Then set, under Settings → Environment Variables:

    PAYWALL_SECRET           signs and verifies licence keys. Generate once
                             (`python -c "import secrets;print(secrets.token_urlsafe(32))"`)
                             and never change it: every key ever issued is
                             verified against it.
    PAYWALL_WEBHOOK_SECRET   the signing secret from the provider's webhook
                             settings. Only api/webhook.py needs it.
    PAYWALL_PROVIDER         lemonsqueezy (the default), paddle or gumroad
    PAYWALL_PRODUCT_IDS      core=aaa,bump=bbb,upsell=ccc,downsell=ddd — how
                             the provider's line items map back to offers
    KV_REST_API_URL          a Redis-compatible REST store (Vercel KV, Upstash)
    KV_REST_API_TOKEN        its token

The store is not optional once money is involved. A serverless function has no filesystem that
survives, so without it devices cannot be counted and a buyer cannot be handed
their key on the thank-you page. On a host that does keep a disk — a small VPS,
a container with a volume — set `PAYWALL_STORE_FILE=/data/grants.jsonl`
instead.

Finally, point the provider's webhook at `https://<your-domain>/api/webhook`
and enable the order-created and order-refunded events.

## Not verified from here

No deployment has been made and no payment has been processed. The handler
shape, the environment variable names and the KV protocol are built from
documentation. Verify each one against a real deployment before driving paid
traffic at it, and test the whole path once in the provider's test mode:
buy, land on the thank-you page, unlock, then refund and confirm the key
stops working.
"""


def write_deployable(
    deploy_dir: Path,
    source_root: Path,
    endpoint_names: tuple[str, ...] = ("unlock", "claim", "webhook"),
    product_path: str = "",
    config: bool = True,
    readme: bool = True,
) -> list[Path]:
    """Write the handlers, the vendored library and (optionally) the host config.

    `config` and `readme` are switchable because a deploy directory is not
    always a directory of our own. Where it is the repository root — a product
    whose notes *are* the repository — a `vercel.json` and a `README.md`
    already belong to someone, and writing ours over theirs would be a
    destructive surprise rather than a build step.
    """
    api = deploy_dir / "api"
    lib = api / "_lib"
    written: list[Path] = []

    # Rebuilt from scratch: a module that stopped being needed should stop
    # being deployed, rather than lingering in the function bundle.
    shutil.rmtree(lib, ignore_errors=True)
    for package, modules in VENDORED.items():
        target = lib / package
        target.mkdir(parents=True, exist_ok=True)
        for module in modules:
            source = source_root / package / module
            if not source.exists():
                raise RuntimeError(f"cannot vendor {source}: it is not there")
            shutil.copyfile(source, target / module)
            written.append(target / module)

    for name in endpoint_names:
        path = api / f"{name}.py"
        path.write_text(_HANDLER.format(name=name), encoding="utf-8")
        written.append(path)

    if config:
        path = deploy_dir / "vercel.json"
        path.write_text(json.dumps(_VERCEL, indent=2) + "\n", encoding="utf-8")
        written.append(path)

    if readme:
        path = deploy_dir / "README.md"
        path.write_text(
            _README.format(
                product_path=product_path or deploy_dir.parent.as_posix(),
                deploy_name=deploy_dir.name,
            ),
            encoding="utf-8",
        )
        written.append(path)
    return written
