"""The three endpoints, as functions of their input.

`unlock` hands over paid content for a valid key. `claim` hands a buyer the
key their purchase produced. `webhook` turns a verified provider callback into
a licence. Each takes what it needs as an argument and returns a status and a
body, so all three are testable without a server, a network or a provider —
which matters, because these are the parts where a mistake either gives the
product away or locks out someone who paid.

Two decisions worth stating.

**A key with no recorded purchase self-registers.** Keys signed by hand — a
comp, a support case, a replacement — carry no grant record, and without one
there is nothing to count devices against. So the first unlock creates the
record. The signature is the authority either way; the record is bookkeeping.

**Errors say as little as the buyer needs and no more.** "That key was not
accepted" covers forged, mistyped and expired alike, because the difference is
only useful to someone probing. The exceptions are the two a buyer can act on:
this licence was withdrawn, and all its devices are in use.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping

from . import licence as licence_mod
from .models import Grant, Product
from .store import Activation, GrantStore

#: What the app is told when a key is refused. Deliberately identical for
#: every reason a key can be invalid.
BAD_KEY = "that key was not accepted"


@dataclass
class Response:
    status: int
    body: dict[str, Any] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return 200 <= self.status < 300


def unlock(
    payload: Mapping[str, Any],
    *,
    product: Product,
    secret: str,
    paid: Mapping[str, Any],
    grants: GrantStore,
    now: float | None = None,
) -> Response:
    """Verify a licence key and return the content it covers."""
    key = str(payload.get("key") or "").strip()
    install = str(payload.get("install") or "").strip()[:64]
    if not key:
        return Response(400, {"error": BAD_KEY})

    try:
        licence = licence_mod.verify(secret, key, product=product, now=now)
    except licence_mod.LicenceError:
        return Response(400, {"error": BAD_KEY})

    grant = grants.by_order(licence.order_id)
    if grant is None:
        grant = Grant(
            order_id=licence.order_id, provider="key", email="",
            codes=licence.codes, key=key, created=now or 0.0,
        )
        grants.put(grant)
    elif grant.revoked:
        return Response(403, {"error": "this licence was withdrawn", "revoked": True})

    seats = product.seats_for(licence.codes)
    activation = grants.activate(licence.order_id, install, seats, now=now)
    if not activation.allowed:
        return Response(403, {"error": activation.reason or "this licence is fully in use"})

    return Response(200, _payload(product, licence.codes, paid, activation))


def claim(
    payload: Mapping[str, Any],
    *,
    product: Product,
    secret: str,
    paid: Mapping[str, Any],
    grants: GrantStore,
    now: float | None = None,
) -> Response:
    """Hand the browser that made a purchase the key it produced.

    The nonce was generated by that browser before it left for the checkout
    and travelled out through the provider's custom data, so possessing it is
    evidence of having started this particular purchase. That is a far better
    bearer token than an order number, which at most providers is short,
    sequential and therefore guessable.

    `peek` returns the key without spending a device slot, for the thank-you
    page to display.
    """
    nonce = str(payload.get("nonce") or "").strip()
    if not nonce or len(nonce) < 12:
        # Short nonces are not ours. Refusing them keeps the endpoint from
        # being a place to try three-character guesses.
        return Response(404, {"error": "no purchase found for this browser"})

    grant = grants.by_nonce(nonce)
    if grant is None:
        return Response(404, {"error": "no purchase found for this browser"})
    if grant.revoked:
        return Response(403, {"error": "this licence was withdrawn", "revoked": True})

    if payload.get("peek"):
        return Response(200, {"key": grant.key, "codes": grant.codes})

    return unlock(
        {"key": grant.key, "install": payload.get("install", "")},
        product=product, secret=secret, paid=paid, grants=grants, now=now,
    )


def webhook(
    raw_body: bytes,
    headers: Mapping[str, str],
    *,
    provider: str,
    product: Product,
    webhook_secret: str,
    licence_secret: str,
    events: Any,
    grants: GrantStore,
    product_ids: Mapping[str, str] | None = None,
    now: float | None = None,
) -> Response:
    """Turn a signed provider callback into a licence, or take one back.

    Imported here rather than at module level so that `unlock` and `claim` do
    not drag the whole storefront in: a serverless function that only reads
    keys should not need the code that parses provider payloads.
    """
    from storefront.fulfil import WebhookError

    from .fulfilment import handle

    try:
        purchase = handle(
            product, provider, raw_body, headers,
            webhook_secret=webhook_secret, licence_secret=licence_secret,
            events=events, grants=grants, product_ids=product_ids, now=now,
        )
    except WebhookError as exc:
        # 400 rather than 500: the provider must not retry a request that will
        # never verify, and a signature failure is worth seeing in the logs.
        return Response(400, {"error": str(exc)})

    body: dict[str, Any] = {"handled": purchase.delivery.delivered}
    if purchase.delivery.duplicate:
        body["duplicate"] = True
    if purchase.revoked:
        body["revoked"] = purchase.revoked
    if purchase.grant is not None:
        body["order"] = purchase.grant.order_id
        body["codes"] = purchase.grant.codes
    if purchase.notes:
        body["notes"] = purchase.notes
    return Response(purchase.http_status, body)


def _payload(
    product: Product, codes: str, paid: Mapping[str, Any], activation: Activation
) -> dict[str, Any]:
    """Exactly what these codes cover, and nothing next to it."""
    wanted = product.grants_for(codes)
    return {
        "codes": codes,
        "seats": activation.seats,
        "used": activation.used,
        "grants": {name: paid[name] for name in wanted if name in paid},
    }
