"""Generated by paywall.deploy — edit paywall/, not this file.

Route: POST /api/unlock
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "_lib"))

from http.server import BaseHTTPRequestHandler          # noqa: E402

from paywall.serverless import (                        # noqa: E402
    ConfigError, demo_warning, dispatch, load_runtime,
)

HERE = os.path.dirname(os.path.abspath(__file__))
_RUNTIME = None


def runtime():
    """Loaded once per instance: the paid bundle is the big part of it."""
    global _RUNTIME
    if _RUNTIME is None:
        _RUNTIME = load_runtime(HERE)
        if warning := demo_warning():
            sys.stderr.write("paywall: %s
" % warning)
    return _RUNTIME


class handler(BaseHTTPRequestHandler):
    def do_POST(self):
        length = int(self.headers.get("content-length") or 0)
        raw = self.rfile.read(length) if length else b""
        try:
            response = dispatch("unlock", raw, dict(self.headers.items()), runtime())
            status, body = response.status, response.body
        except ConfigError as exc:
            # A deployment mistake, not a bad request. Say so in the log and
            # keep the message out of the response body.
            sys.stderr.write("paywall: %s\n" % exc)
            status, body = 500, {"error": "this endpoint is not configured yet"}
        self._send(status, body)

    def do_GET(self):
        self._send(405, {"error": "post to this endpoint"})

    def _send(self, status, body):
        payload = json.dumps(body).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, fmt, *args):
        # The default writes the client's address into the log on every
        # request. The platform already logs the request line.
        sys.stderr.write("paywall unlock: " + (fmt % args) + "\n")
